name: Tests
run-name: Execute all tests using Mocha and update coverage badges
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  statuses: write
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup github-actions[bot] git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: HUSKY=0 pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Update test coverage badges in README
        run: pnpm make-badges

      - name: Check for changes
        id: changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "changes_exist=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes_exist=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Output if changes exist
        env:
          CHANGES_EXIST: ${{ steps.changes.outputs.changes_exist }}
        run: echo "$CHANGES_EXIST"

      - name: Update README test coverage badges via GitHub Actions, if changes exist
        if: steps.changes.outputs.changes_exist == 'true'
        run: |
          git commit -m "docs: update test coverage badges via GitHub Actions"
          git push
